# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_INNOSETUP "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl")
set(CPACK_CMAKE_GENERATOR "Visual Studio 17 2022")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "QGroundControl built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl;QGroundControl;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/staging")
set(CPACK_MODULE_PATH "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/cmake;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/kwin;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/kwin;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;C:/Qt/6.6.3/msvc2019_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_CONTACT "karney@alum.mit.edu")
set(CPACK_NSIS_DISPLAY_NAME "GeographicLib x64 2.4")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_HELP_LINK "mailto:karney@alum.mit.edu")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "C:\\Program Files")
set(CPACK_NSIS_MENU_LINKS "https://geographiclib.sourceforge.io/C++/2.4/index.html;Library documentation;https://geographiclib.sourceforge.io/C++/2.4/utilities.html;Utilities documentation;https://geographiclib.sourceforge.io;GeographicLib home page;https://sourceforge.net/projects/geographiclib/;Main project page")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "GeographicLib x64 2.4")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://geographiclib.sourceforge.io")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "karney@alum.mit.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GeographicLib library, utilities, and documentation")
set(CPACK_PACKAGE_FILE_NAME "GeographicLib-2.4-win64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://qgroundcontrol.com/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GeographicLib-2.4")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GeographicLib-x64-2.4")
set(CPACK_PACKAGE_NAME "QGroundControl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "GeographicLib")
set(CPACK_PACKAGE_VERSION "2.4")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "4")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "#;~$;/\\.git;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/BUILD;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/man/(.*\\.pod|makeusage\\.sh|dummy\\..*)$;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/cmake/maintainer-.*\\.cmake$;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/(develop|cgi-bin|.*\\.cache)/;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/(data-distrib|data-installer)/;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/(archive|scratch|mpfr_mpir_x86_x64_msvc2010)/;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/.*\\.(zip|tar\\.gz|bak|lsp)$;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/(autogen|biblio)\\.sh$;C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/_deps/geographiclib-src/(makefile-admin|HOWTO-RELEASE.txt)$")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "GeographicLib-2.4")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/adrie/Desktop/Boulot/MAVLINK/forkQGroundControl/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
