// This file is autogenerated. Changes will be overwritten.
#include <EWIEGA46WW/moc_MavlinkCameraControl.cpp>
#include <EWIEGA46WW/moc_QGCCameraManager.cpp>
#include <EWIEGA46WW/moc_SimulatedCameraControl.cpp>
